import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useRef, useState } from "react";
import {
  ArrowRight,
  CheckCircle2,
  CloudUpload,
  FileText,
  Hammer,
  Lightbulb,
  Loader2,
  Plus,
  Rocket,
  Scale,
  Sparkles,
  Star,
  Briefcase,
  X,
  ArrowUp,
  HandHelping,
  PauseCircle,
  AlertCircle,
  Calendar,
} from "lucide-react";
import { buildGoogleCalendarUrl } from "@/lib/google-calendar";
import type { Profile, TechItem } from "@/lib/loop-types";
import { logActivity, setLoopState, useLoop } from "@/lib/loop-store";
import { GoogleSignIn } from "@/components/GoogleSignIn";
import {
  aiAnalyzeResume,
  aiFollowUpQuestions,
  aiGeneratePlan,
  aiSuggestProjects,
} from "@/lib/sarvam.functions";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Start here — BuildMyLogic" },
      {
        name: "description",
        content:
          "Upload your resume, answer a few questions and BuildMyLogic's AI builds your personal project path, missions and daily sessions.",
      },
      { property: "og:title", content: "Start here — BuildMyLogic" },
      {
        property: "og:description",
        content:
          "From resume to a real project plan in under two minutes, generated by AI.",
      },
    ],
  }),
  component: Introduction,
});

const GOALS = [
  { label: "Learn a skill", icon: Lightbulb, detail: "Which skill?" },
  {
    label: "Build a real product",
    icon: Hammer,
    detail: "What kind of product?",
  },
  { label: "Prepare for a job", icon: Briefcase, detail: "Which role?" },
  {
    label: "Turn an idea into product",
    icon: Rocket,
    detail: "What's the idea?",
  },
] as const;

const EXPERIENCE = [
  { label: "Yes, and succeeded", icon: CheckCircle2 },
  { label: "Yes, but got stuck", icon: AlertCircle },
  { label: "Started but never finished", icon: PauseCircle },
  { label: "First time building", icon: Star },
] as const;

const CHALLENGE = [
  { label: "Push me", icon: ArrowUp },
  { label: "Balance me", icon: Scale },
  { label: "Guide me", icon: HandHelping },
] as const;

const LEVELS: TechItem["level"][] = ["beginner", "intermediate", "advanced"];

const emptyProfile: Profile = {
  name: "",
  resumeText: "",
  resumeSummary: "",
  technologies: [],
  goal: "",
  goalDetail: "",
  experience: "",
  experienceDetail: "",
  startTime: "19:00",
  endTime: "21:00",
  repeatDaily: true,
  followUps: [],
  projectIdea: "",
  challenge: "",
};

async function extractText(file: File): Promise<string> {
  if (file.name.toLowerCase().endsWith(".pdf")) {
    const pdfjs = await import("pdfjs-dist");
    const workerUrl = (await import("pdfjs-dist/build/pdf.worker.min.mjs?url"))
      .default;
    pdfjs.GlobalWorkerOptions.workerSrc = workerUrl;
    const doc = await pdfjs.getDocument({ data: await file.arrayBuffer() })
      .promise;
    let out = "";
    for (let page = 1; page <= Math.min(doc.numPages, 6); page += 1) {
      const content = await (await doc.getPage(page)).getTextContent();
      out += `${content.items.map((i) => ("str" in i ? i.str : "")).join(" ")}\n`;
    }
    return out;
  }
  if (file.name.toLowerCase().endsWith(".docx")) {
    const mammoth = await import("mammoth");
    const result = await mammoth.extractRawText({
      arrayBuffer: await file.arrayBuffer(),
    });
    return result.value;
  }
  return await file.text();
}

function Introduction() {
  const state = useLoop();
  const navigate = useNavigate();
  const [screen, setScreen] = useState(0);
  const [profile, setProfile] = useState<Profile>(emptyProfile);
  const [newTech, setNewTech] = useState("");
  const [resumeFile, setResumeFile] = useState<string | null>(null);
  const [resumeBusy, setResumeBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const [followUps, setFollowUps] = useState<
    { question: string; placeholder: string }[]
  >([]);
  const [followAnswers, setFollowAnswers] = useState<string[]>([]);
  const [projects, setProjects] = useState<
    { title: string; summary: string; stack: string; why: string }[]
  >([]);
  const [chosenProject, setChosenProject] = useState<number | null>(null);
  const [customIdea, setCustomIdea] = useState("");
  const fileInput = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (state.onboarded && state.plan) void navigate({ to: "/dashboard" });
  }, [state.onboarded, state.plan, navigate]);

  const patch = (values: Partial<Profile>) =>
    setProfile((prev) => ({ ...prev, ...values }));

  async function onFile(file: File | undefined) {
    if (!file) return;
    setError(null);
    setResumeFile(file.name);
    setResumeBusy(true);
    try {
      const text = await extractText(file);
      if (!text.trim())
        throw new Error("We couldn't read any text out of that file.");
      const result = await aiAnalyzeResume({ data: { text } });
      patch({
        resumeText: text.slice(0, 12000),
        resumeSummary: result.summary ?? "",
        name: result.name?.split(" ")[0] ?? "",
        technologies: (result.technologies ?? []).filter((t) => t?.name),
        experience: result.experience ?? "",
      });
      setScreen(2);
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Couldn't analyze your resume. You can continue manually.",
      );
    } finally {
      setResumeBusy(false);
    }
  }

  async function loadFollowUps() {
    setBusy("Thinking about what else it needs to know…");
    setError(null);
    try {
      const result = await aiFollowUpQuestions({ data: { profile } });
      const questions = (result.questions ?? []).slice(0, 3);
      setFollowUps(questions);
      setFollowAnswers(questions.map(() => ""));
      setScreen(6);
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Sarvam AI is unavailable right now.",
      );
    } finally {
      setBusy(null);
    }
  }

  async function loadProjects() {
    const withAnswers: Profile = {
      ...profile,
      followUps: followUps.map((q, i) => ({
        question: q.question,
        answer: followAnswers[i] ?? "",
      })),
    };
    setProfile(withAnswers);
    setBusy("Generating project ideas from your background…");
    setError(null);
    try {
      const result = await aiSuggestProjects({
        data: { profile: withAnswers },
      });
      setProjects(result.projects ?? []);
      setScreen(7);
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Sarvam AI is unavailable right now.",
      );
    } finally {
      setBusy(null);
    }
  }

  async function build(challenge: string) {
    const selectedProject =
      chosenProject !== null ? projects[chosenProject] : null;
    const idea =
      customIdea.trim() ||
      (selectedProject
        ? `${selectedProject.title} — ${selectedProject.summary} (Required stack: ${selectedProject.stack})`
        : "");
    // A suggested project's stack is the learner's explicit choice for this path.
    // Preserve it in their profile so the plan generator cannot silently switch stacks.
    const selectedStack = selectedProject?.stack.trim();
    const finalProfile: Profile = {
      ...profile,
      challenge,
      projectIdea: idea,
      technologies: selectedStack
        ? [{ name: selectedStack, level: "beginner" }]
        : profile.technologies,
    };
    setProfile(finalProfile);
    setBusy("Designing your build path…");
    setError(null);
    try {
      const plan = await aiGeneratePlan({ data: { profile: finalProfile } });
      setLoopState((prev) => ({
        ...prev,
        onboarded: true,
        profile: finalProfile,
        plan: {
          ...plan,
          // BuildMyLogic skill scores are earned from activity, not inferred from a resume or onboarding claim.
          skills: (plan.skills ?? []).map((skill) => ({
            ...skill,
            level: 0,
            note: "No BuildMyLogic evidence yet. Build and prove it.",
          })),
        },
        missionProgress: Object.fromEntries(
          (plan.missions ?? []).map((m, i) => [
            m.id,
            {
              status: i === 0 ? "active" : "locked",
              completedSteps: [],
            } as const,
          ]),
        ),
      }));
      logActivity({
        kind: "ai",
        text: `AI generated your path for “${plan.projectTitle}”`,
      });
      setScreen(9);
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Sarvam AI is unavailable right now.",
      );
      setScreen(8);
    } finally {
      setBusy(null);
    }
  }

  const heading =
    "display text-[34px] font-extrabold leading-tight sm:text-[40px]";
  const sub = "mt-2 text-sm text-muted-foreground";
  const step = (n: string) => (
    <p className="mb-3 text-[11px] font-bold uppercase tracking-[0.14em] text-muted-foreground">
      {n}
    </p>
  );

  return (
    <div
      className={`mx-auto flex min-h-screen w-full flex-col px-5 py-10 sm:px-6 sm:py-12 ${screen === 0 ? "max-w-6xl" : "max-w-3xl"}`}
    >
      <header className="mb-12 flex items-start justify-between gap-6">
        <div>
          <p className="display text-[32px] font-extrabold">BuildMyLogic</p>
          <p className="text-[13px] text-muted-foreground">
            From Learning to Real-World Building.
          </p>
        </div>
        <div className="pt-1">
          <GoogleSignIn />
        </div>
      </header>

      {error && (
        <div className="mb-6 rounded-xl border border-border bg-surface px-4 py-3 text-xs font-medium text-destructive">
          {error}
        </div>
      )}

      {busy && (
        <div className="card-surface mb-6 flex items-center gap-3 px-5 py-4">
          <Loader2 className="h-4 w-4 animate-spin text-primary" />
          <span className="text-sm font-medium">{busy}</span>
        </div>
      )}

      {/* 0 — welcome */}
      {screen === 0 && (
        <section className="rise">
          <div className="grid items-center gap-12 lg:grid-cols-[1.05fr_0.95fr]">
            <div>
              <span className="pill border border-primary/20 bg-primary-soft text-accent-foreground">
                <Sparkles className="h-3 w-3" /> AI-built learning path
              </span>

              <h1 className="display mt-6 text-[46px] font-extrabold leading-[1.02] tracking-[-0.045em] sm:text-[64px]">
                Stop learning.
                <br />
                <span className="text-primary">Start building.</span>
              </h1>

              <p className="mt-6 max-w-xl text-[17px] leading-relaxed text-muted-foreground">
                Why do fresh graduates struggle to build real-world software
                despite years of theory?
              </p>

              <p className="mt-5 max-w-xl border-l-4 border-primary pl-4 text-[19px] font-semibold leading-snug">
                Because knowing how something works isn&apos;t the same as
                knowing how to build with it.
              </p>

              <div className="mt-8 flex flex-col items-start gap-3 sm:flex-row sm:items-center">
                <button
                  type="button"
                  className="btn-base btn-ink btn-ink-hover px-7 py-3.5 text-[15px]"
                  onClick={() => setScreen(1)}
                >
                  Get Started <ArrowRight className="h-4 w-4" />
                </button>
                <span className="text-[12px] font-medium text-muted-foreground">
                  Takes less than 2 minutes · no credit card
                </span>
              </div>

              <div className="mt-10 grid max-w-lg grid-cols-3 gap-3 border-t border-border pt-6">
                {[
                  { value: "6 steps", label: "from resume to project plan" },
                  { value: "Vibe", label: "hints when you stall" },
                  { value: "VS Code", label: "sessions sync instantly" },
                ].map((item) => (
                  <div key={item.value}>
                    <p className="display text-[19px] font-extrabold tracking-[-0.03em]">
                      {item.value}
                    </p>
                    <p className="mt-0.5 text-[11px] leading-4 text-muted-foreground">
                      {item.label}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            {/* Product preview — shows what the learner actually gets. */}
            <div className="relative">
              <div className="card-surface px-5 py-5 sm:px-6 sm:py-6">
                <div className="flex items-center justify-between">
                  <p className="eyebrow">Live mission</p>
                  <span className="pill bg-emerald-50 text-emerald-700">
                    <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-500" />{" "}
                    In sync
                  </span>
                </div>

                <h3 className="display mt-3 text-[19px] font-extrabold tracking-[-0.03em]">
                  Build a CLI calculator
                </h3>
                <p className="mt-1 text-[13px] text-muted-foreground">
                  Python · conditions and operators
                </p>

                <div className="mt-4 h-1.5 w-full overflow-hidden rounded-full bg-muted">
                  <div className="h-full w-1/2 rounded-full bg-primary" />
                </div>
                <div className="mt-2 flex items-center justify-between text-[11px] font-semibold text-muted-foreground">
                  <span>2 of 4 checkpoints verified</span>
                  <span>50%</span>
                </div>

                <ul className="mt-4 space-y-2.5">
                  {[
                    {
                      label: "Read two numbers from the user",
                      state: "Verified",
                    },
                    { label: "Support +, -, * and /", state: "Detected" },
                    {
                      label: "Guard against division by zero",
                      state: "Not verified",
                    },
                  ].map((row) => (
                    <li
                      key={row.label}
                      className="flex items-start gap-2.5 text-[13px]"
                    >
                      <CheckCircle2
                        className={`mt-0.5 h-4 w-4 flex-none ${row.state === "Not verified" ? "text-muted-foreground/50" : row.state === "Detected" ? "text-primary" : "text-emerald-500"}`}
                      />
                      <span className="flex-1 leading-5">{row.label}</span>
                      <span className="pt-0.5 text-[10px] font-bold uppercase tracking-wide text-muted-foreground">
                        {row.state}
                      </span>
                    </li>
                  ))}
                </ul>
              </div>

              <div className="card-surface absolute -bottom-6 -left-4 hidden w-[240px] px-4 py-3 sm:block">
                <p className="eyebrow">Vibe</p>
                <p className="mt-1 text-[13px] leading-5">
                  Move the zero check above the division and run it again.
                </p>
              </div>
            </div>
          </div>

          <div className="mt-20 grid gap-4 sm:grid-cols-3">
            {[
              {
                icon: Hammer,
                title: "Build, don't binge",
                body: "No endless tutorials. You learn what you need, when you need it — by building.",
              },
              {
                icon: Lightbulb,
                title: "Hints at the right moment",
                body: "Vibe watches your tests and errors, then gives one short hint instead of the answer.",
              },
              {
                icon: Rocket,
                title: "Proof you can show",
                body: "Every mission ends with checked evidence, so “I know it” becomes “I built it”.",
              },
            ].map((item) => (
              <div
                key={item.title}
                className="card-surface card-hover px-5 py-5"
              >
                <span className="grid h-9 w-9 place-items-center rounded-xl bg-primary-soft text-accent-foreground">
                  <item.icon className="h-4.5 w-4.5" />
                </span>
                <p className="mt-3 text-[15px] font-bold">{item.title}</p>
                <p className="mt-1.5 text-[13px] leading-5 text-muted-foreground">
                  {item.body}
                </p>
              </div>
            ))}
          </div>

          <div className="mt-10 flex flex-wrap items-center gap-3 text-[12px] font-semibold text-muted-foreground">
            <span className="text-foreground">We take you from</span>
            {[
              "theory",
              "hands-on practice",
              "real-world projects",
              "feedback",
              "improvement",
            ].map((s) => (
              <span
                key={s}
                className="rounded-md border border-border bg-surface px-2.5 py-1.5"
              >
                {s}
              </span>
            ))}
            <span className="rounded-md border border-primary bg-primary-soft px-2.5 py-1.5 text-accent-foreground">
              job readiness
            </span>
          </div>
        </section>
      )}

      {/* 1 — resume */}
      {screen === 1 && (
        <section>
          {step("Start here")}
          <h2 className={heading}>Start with your resume.</h2>
          <p className={sub}>
            Let BuildMyLogic understand what you already know before deciding
            what you should build.
          </p>

          {resumeFile && (
            <div className="card-surface mt-7 flex items-center justify-between px-4 py-3.5">
              <span className="flex items-center gap-2.5 truncate text-sm font-semibold">
                <FileText className="h-4 w-4" /> {resumeFile}
              </span>
              <button
                type="button"
                aria-label="Remove resume"
                onClick={() => {
                  setResumeFile(null);
                  patch({ resumeText: "", resumeSummary: "" });
                }}
                className="text-muted-foreground hover:text-foreground"
              >
                <X className="h-4 w-4" />
              </button>
            </div>
          )}

          <button
            type="button"
            onClick={() => fileInput.current?.click()}
            disabled={resumeBusy}
            className="mt-6 w-full rounded-2xl border-2 border-dashed border-input bg-surface px-7 py-14 text-center transition-colors hover:border-foreground disabled:opacity-70"
          >
            {resumeBusy ? (
              <>
                <Loader2 className="mx-auto mb-4 h-7 w-7 animate-spin text-primary" />
                <p className="text-[17px] font-bold">Analyzing your resume…</p>
                <p className="mt-1 text-[13px] text-muted-foreground">
                  Detecting technologies, projects and experience
                </p>
              </>
            ) : (
              <>
                <CloudUpload className="mx-auto mb-4 h-7 w-7" />
                <p className="text-[17px] font-bold">Drop your resume here</p>
                <p className="mt-1 text-[13px] text-muted-foreground">
                  PDF, DOCX or TXT
                </p>
                <span className="btn-base btn-ink mt-5">Upload Resume</span>
              </>
            )}
          </button>
          <input
            ref={fileInput}
            type="file"
            accept=".pdf,.docx,.txt,.md"
            className="hidden"
            onChange={(event) => void onFile(event.target.files?.[0])}
          />

          <div className="mt-5 text-center">
            <button
              type="button"
              className="text-[13px] font-medium text-muted-foreground underline hover:text-foreground"
              onClick={() => setScreen(2)}
            >
              Continue without a resume
            </button>
          </div>

          <div className="mt-8">
            <button
              type="button"
              className="btn-base btn-outline"
              onClick={() => setScreen(0)}
            >
              Back
            </button>
          </div>
        </section>
      )}

      {/* 2 — technologies */}
      {screen === 2 && (
        <section>
          {step("Question 1 of 6")}
          <h2 className={heading}>What technologies do you know?</h2>
          <p className={sub}>Select your skill level for each</p>
          {profile.resumeSummary && (
            <p className="pill mt-4 bg-primary-soft text-accent-foreground">
              <Sparkles className="h-3 w-3" /> AI-detected from your resume —
              you can edit anything
            </p>
          )}

          <div className="mt-6 space-y-3">
            {profile.technologies.map((tech, index) => (
              <div
                key={`${tech.name}-${index}`}
                className="card-surface flex items-center justify-between gap-3 px-4 py-3"
              >
                <span className="truncate text-sm font-semibold">
                  {tech.name}
                </span>
                <div className="flex items-center gap-1.5">
                  {LEVELS.map((level) => (
                    <button
                      key={level}
                      type="button"
                      onClick={() =>
                        patch({
                          technologies: profile.technologies.map((t, i) =>
                            i === index ? { ...t, level } : t,
                          ),
                        })
                      }
                      className={`rounded-lg border px-2.5 py-1.5 text-[11px] font-semibold capitalize transition-colors ${
                        tech.level === level
                          ? "border-ink bg-ink text-ink-foreground"
                          : "border-border bg-surface hover:bg-muted"
                      }`}
                    >
                      {level}
                    </button>
                  ))}
                  <button
                    type="button"
                    aria-label={`Remove ${tech.name}`}
                    onClick={() =>
                      patch({
                        technologies: profile.technologies.filter(
                          (_, i) => i !== index,
                        ),
                      })
                    }
                    className="ml-1 text-muted-foreground hover:text-destructive"
                  >
                    <X className="h-3.5 w-3.5" />
                  </button>
                </div>
              </div>
            ))}
          </div>

          <div className="mt-4 flex gap-2">
            <input
              value={newTech}
              onChange={(event) => setNewTech(event.target.value)}
              onKeyDown={(event) => {
                if (event.key === "Enter" && newTech.trim()) {
                  patch({
                    technologies: [
                      ...profile.technologies,
                      { name: newTech.trim(), level: "beginner" },
                    ],
                  });
                  setNewTech("");
                }
              }}
              placeholder="Add another technology..."
              className="flex-1 rounded-xl border border-input bg-surface px-4 py-3 text-sm outline-none focus:border-foreground"
            />
            <button
              type="button"
              aria-label="Add technology"
              className="btn-base btn-ink px-4"
              onClick={() => {
                if (!newTech.trim()) return;
                patch({
                  technologies: [
                    ...profile.technologies,
                    { name: newTech.trim(), level: "beginner" },
                  ],
                });
                setNewTech("");
              }}
            >
              <Plus className="h-4 w-4" />
            </button>
          </div>

          <div className="mt-8 flex gap-3">
            <button
              type="button"
              className="btn-base btn-outline"
              onClick={() => setScreen(1)}
            >
              Back
            </button>
            <button
              type="button"
              className="btn-base btn-ink btn-ink-hover disabled:opacity-40"
              disabled={profile.technologies.length === 0}
              onClick={() => setScreen(3)}
            >
              Next
            </button>
          </div>
        </section>
      )}

      {/* 3 — goal */}
      {screen === 3 && (
        <section>
          {step("Question 2 of 6")}
          <h2 className={heading}>What's your primary goal?</h2>
          <p className={sub}>
            This shapes the projects BuildMyLogic generates for you — you can
            change it anytime.
          </p>
          <div className="mt-6 space-y-3">
            {GOALS.map(({ label, icon: Icon }) => (
              <button
                key={label}
                type="button"
                onClick={() => patch({ goal: label })}
                className={`flex w-full items-center gap-3 rounded-xl border px-4 py-3.5 text-left text-sm font-medium transition-colors ${
                  profile.goal === label
                    ? "border-ink bg-ink text-ink-foreground"
                    : "border-border bg-surface hover:bg-muted"
                }`}
              >
                <Icon className="h-4 w-4" /> {label}
              </button>
            ))}
          </div>
          {profile.goal && (
            <div className="mt-5">
              <label className="text-xs font-semibold text-muted-foreground">
                {GOALS.find((g) => g.label === profile.goal)?.detail}
              </label>
              <input
                value={profile.goalDetail}
                onChange={(event) => patch({ goalDetail: event.target.value })}
                className="mt-2 w-full rounded-xl border border-input bg-surface px-4 py-3 text-sm outline-none focus:border-foreground"
              />
            </div>
          )}
          <div className="mt-8 flex gap-3">
            <button
              type="button"
              className="btn-base btn-outline"
              onClick={() => setScreen(2)}
            >
              Back
            </button>
            <button
              type="button"
              className="btn-base btn-ink btn-ink-hover disabled:opacity-40"
              disabled={!profile.goal}
              onClick={() => setScreen(4)}
            >
              Next
            </button>
          </div>
        </section>
      )}

      {/* 4 — experience */}
      {screen === 4 && (
        <section>
          {step("Question 3 of 6")}
          <h2 className={heading}>Have you built projects before?</h2>
          <p className={sub}>This helps us gauge challenge level</p>
          <div className="mt-6 space-y-3">
            {EXPERIENCE.map(({ label, icon: Icon }) => (
              <button
                key={label}
                type="button"
                onClick={() => patch({ experience: label })}
                className={`flex w-full items-center gap-3 rounded-xl border px-4 py-3.5 text-left text-sm font-medium transition-colors ${
                  profile.experience === label
                    ? "border-ink bg-ink text-ink-foreground"
                    : "border-border bg-surface hover:bg-muted"
                }`}
              >
                <Icon className="h-4 w-4" /> {label}
              </button>
            ))}
          </div>
          <textarea
            value={profile.experienceDetail}
            onChange={(event) =>
              patch({ experienceDetail: event.target.value })
            }
            placeholder="Tell us more about your experience..."
            rows={3}
            className="mt-5 w-full rounded-xl border border-input bg-surface px-4 py-3 text-sm outline-none focus:border-foreground"
          />
          <div className="mt-8 flex gap-3">
            <button
              type="button"
              className="btn-base btn-outline"
              onClick={() => setScreen(3)}
            >
              Back
            </button>
            <button
              type="button"
              className="btn-base btn-ink btn-ink-hover disabled:opacity-40"
              disabled={!profile.experience}
              onClick={() => setScreen(5)}
            >
              Next
            </button>
          </div>
        </section>
      )}

      {/* 5 — schedule */}
      {screen === 5 && (
        <section>
          {step("Question 4 of 6")}
          <h2 className={heading}>When can you dedicate time?</h2>
          <p className={sub}>
            This sizes the project BuildMyLogic generates for you
          </p>
          <div className="card-surface mt-6 px-6 py-6">
            <div className="flex flex-wrap gap-5">
              <label className="text-xs font-semibold text-muted-foreground">
                Start Time
                <input
                  type="time"
                  value={profile.startTime}
                  onChange={(event) => patch({ startTime: event.target.value })}
                  className="mt-2 block rounded-xl border border-input bg-surface px-4 py-2.5 text-sm outline-none focus:border-foreground"
                />
              </label>
              <label className="text-xs font-semibold text-muted-foreground">
                End Time
                <input
                  type="time"
                  value={profile.endTime}
                  onChange={(event) => patch({ endTime: event.target.value })}
                  className="mt-2 block rounded-xl border border-input bg-surface px-4 py-2.5 text-sm outline-none focus:border-foreground"
                />
              </label>
            </div>
            <div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-border pt-4">
              <label className="flex items-center gap-2 text-sm">
                <input
                  type="checkbox"
                  checked={profile.repeatDaily}
                  onChange={(event) =>
                    patch({ repeatDaily: event.target.checked })
                  }
                  className="h-4 w-4 accent-[var(--color-primary)]"
                />
                Repeat this schedule daily
              </label>

              <button
                type="button"
                onClick={() => {
                  const url = buildGoogleCalendarUrl({
                    startTime: profile.startTime || "19:00",
                    endTime: profile.endTime || "20:00",
                    repeatDaily: profile.repeatDaily ?? true,
                    reminderMinutes: 15,
                    missionTitle: "Daily Logic Build",
                  });
                  window.open(url, "_blank", "noopener,noreferrer");
                }}
                className="inline-flex items-center gap-1.5 text-xs font-semibold text-primary hover:underline"
              >
                <Calendar className="h-3.5 w-3.5" />
                <span>Test Add to Google Calendar ↗</span>
              </button>
            </div>
          </div>
          <div className="mt-8 flex gap-3">
            <button
              type="button"
              className="btn-base btn-outline"
              onClick={() => setScreen(4)}
            >
              Back
            </button>
            <button
              type="button"
              className="btn-base btn-ink btn-ink-hover"
              onClick={() => void loadFollowUps()}
            >
              Next
            </button>
          </div>
        </section>
      )}

      {/* 6 — AI follow-ups */}
      {screen === 6 && (
        <section>
          {step("Question 5 of 6")}
          <h2 className={heading}>A few things the AI still wants to know.</h2>
          <p className={sub}>
            Sarvam AI wrote these questions after reading your answers and
            resume.
          </p>
          <div className="mt-6 space-y-5">
            {followUps.map((item, index) => (
              <div key={item.question}>
                <p className="text-sm font-semibold">{item.question}</p>
                <input
                  value={followAnswers[index] ?? ""}
                  placeholder={item.placeholder}
                  onChange={(event) =>
                    setFollowAnswers((prev) =>
                      prev.map((a, i) =>
                        i === index ? event.target.value : a,
                      ),
                    )
                  }
                  className="mt-2 w-full rounded-xl border border-input bg-surface px-4 py-3 text-sm outline-none focus:border-foreground"
                />
              </div>
            ))}
          </div>
          <div className="mt-8 flex gap-3">
            <button
              type="button"
              className="btn-base btn-outline"
              onClick={() => setScreen(5)}
            >
              Back
            </button>
            <button
              type="button"
              className="btn-base btn-ink btn-ink-hover disabled:opacity-40"
              disabled={followAnswers.every((a) => !a.trim())}
              onClick={() => void loadProjects()}
            >
              Next
            </button>
          </div>
        </section>
      )}

      {/* 7 — project choice */}
      {screen === 7 && (
        <section>
          {step("Question 6 of 6")}
          <h2 className={heading}>What do you want to build?</h2>
          <p className={sub}>
            BuildMyLogic generated these starting points from your background.
          </p>
          <div className="mt-6 grid gap-3 sm:grid-cols-2">
            {projects.map((project, index) => (
              <button
                key={project.title}
                type="button"
                onClick={() => {
                  setChosenProject(index);
                  setCustomIdea("");
                }}
                className={`card-surface p-5 text-left transition-colors ${
                  chosenProject === index
                    ? "border-primary bg-primary-soft"
                    : "hover:bg-muted"
                }`}
              >
                <p className="text-sm font-bold">{project.title}</p>
                <p className="mt-1.5 text-xs leading-relaxed text-muted-foreground">
                  {project.summary}
                </p>
                <p className="mt-3 text-[11px] font-semibold text-accent-foreground">
                  {project.stack}
                </p>
                <p className="mt-2 text-[11px] italic text-muted-foreground">
                  {project.why}
                </p>
              </button>
            ))}
          </div>
          <p className="mt-6 text-[13px] font-medium">
            Already have an idea? Describe it and BuildMyLogic will turn it into
            a build plan.
          </p>
          <textarea
            value={customIdea}
            rows={3}
            placeholder="Describe your project idea..."
            onChange={(event) => {
              setCustomIdea(event.target.value);
              if (event.target.value.trim()) setChosenProject(null);
            }}
            className="mt-2 w-full rounded-xl border border-input bg-surface px-4 py-3 text-sm outline-none focus:border-foreground"
          />
          <div className="mt-8 flex gap-3">
            <button
              type="button"
              className="btn-base btn-outline"
              onClick={() => setScreen(6)}
            >
              Back
            </button>
            <button
              type="button"
              className="btn-base btn-ink btn-ink-hover disabled:opacity-40"
              disabled={chosenProject === null && !customIdea.trim()}
              onClick={() => setScreen(8)}
            >
              Next
            </button>
          </div>
        </section>
      )}

      {/* 8 — challenge */}
      {screen === 8 && (
        <section>
          {step("Last one")}
          <h2 className={heading}>How do you want to be challenged?</h2>
          <p className={sub}>Choose your learning approach</p>
          <div className="mt-6 space-y-3">
            {CHALLENGE.map(({ label, icon: Icon }) => (
              <button
                key={label}
                type="button"
                disabled={busy !== null}
                onClick={() => {
                  patch({ challenge: label });
                  void build(label);
                }}
                className={`flex w-full items-center gap-3 rounded-xl border px-4 py-3.5 text-left text-sm font-medium transition-colors disabled:opacity-60 ${
                  profile.challenge === label
                    ? "border-ink bg-ink text-ink-foreground"
                    : "border-border bg-surface hover:bg-muted"
                }`}
              >
                <Icon className="h-4 w-4" /> {label}
              </button>
            ))}
          </div>
          <div className="mt-8">
            <button
              type="button"
              className="btn-base btn-outline"
              onClick={() => setScreen(7)}
            >
              Back
            </button>
          </div>
        </section>
      )}

      {/* 9 — done */}
      {screen === 9 && state.plan && (
        <section className="text-center">
          <Sparkles className="mx-auto h-9 w-9 text-primary" />
          <h2 className="display mt-5 text-[34px] font-extrabold">
            {state.plan.headline}
          </h2>
          <p className="mt-3 text-sm text-muted-foreground">
            {state.plan.profileSummary}
          </p>
          <div className="card-surface mx-auto mt-8 max-w-xl px-6 py-6 text-left">
            <p className="text-[11px] font-bold uppercase tracking-[0.14em] text-muted-foreground">
              Your project
            </p>
            <p className="mt-2 text-lg font-bold">{state.plan.projectTitle}</p>
            <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
              {state.plan.projectPitch}
            </p>
            <dl className="mt-5 grid grid-cols-2 gap-4 text-sm">
              <div>
                <dt className="text-xs text-muted-foreground">Missions</dt>
                <dd className="font-bold">
                  {state.plan.missions?.length ?? 0}
                </dd>
              </div>
              <div>
                <dt className="text-xs text-muted-foreground">Daily window</dt>
                <dd className="font-bold">
                  {profile.startTime}–{profile.endTime}
                </dd>
              </div>
            </dl>
          </div>
          <button
            type="button"
            className="btn-base btn-ink btn-ink-hover mx-auto mt-9 px-7 py-3.5 text-[15px]"
            onClick={() => void navigate({ to: "/dashboard" })}
          >
            Enter your dashboard <ArrowRight className="h-4 w-4" />
          </button>
        </section>
      )}
    </div>
  );
}
